#!/usr/bin/env bash
if [ -a ~/.bashrc ]; then
    source ~/.bashrc
fi
repo_name=tdd-demo
cd ~/"$repo_name"

sudo apt-get update
sudo apt-get install -y python3-venv
sudo apt-get install -y meld
sudo apt-get install -y tmux
deactivate 2>>/dev/null
if [ ! \( -a env \) ]; then
    python3 -m venv env
fi
source env/bin/activate
pip install -r requirements.txt

# do each startup
tmux kill-session -t "$repo_name"
tmux new -s "$repo_name" bash --rcfile pytest-window-bashrc \; split-window -h bash --rcfile git-status-bashrc \; split-window -p 75 bash --rcfile misc-bashrc \;
